/****************************************************************************************
*@Copyrights  2012，中兴软创（南京）计算机有限公司 开发部 CCB项目--QuickMDB小组
*@            All rights reserved.
*@Name：	    mdbErrorHelper.cpp		
*@Description： mdb错误码帮助类
*@Author:	jin.shaohua
*@Date：	    2012.07
*@History:
******************************************************************************************/
#include "Helper/mdbErrorHelper.h"
#include "Helper/mdbStruct.h"
#include "Helper/mdbOS.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>

//#include "BillingSDK.h"
//using namespace ZSmart::BillingSDK;

//namespace QuickMDB{

//CODE:BREIF:CAUSE:ACTION
TMdbError g_mdbErrors[] =
{
    {0,"normal, successful completion", 
        "An operation has completed normally, having met no exceptions.", 
        "No action required."},
    {40000,"Unknow Error ", 
            "For an unknown reason.", 
            "Please contact QMDB Admin."},
    {20001,"DSN does not exist.", 
            "DSN does not exist.", 
            "Please check dsn config."},
    {20002,"user does not exist.", 
            "Invalid username.", 
            "Use a valid username and retry."},
    {20003,"Password is incorrect.", 
            "Password is wrong for the login username.",
            "Correct the password and retry."},
    {20004,"user does not have privilege to the operation.",
            "user does not have privilege to the operation.",
            "Please use the administrator user."},
    {20005,"QMDB was not created.", 
            "QMDB was not created.", 
            "Please create QMDB first."},
    {20006,"QMDB has already created.", 
            "QMDB has already created.", 
            "Please destroy QMDB first."},
    {20007,"QMDB was not connected.", 
            "QMDB was not connected.", 
            "Please connect the QMDB."},
    {20008,"failed to connect DSN,connection to QMDB refused",
            "failed to connect DSN,connection to QMDB refused",
            "Please check the correct user name, password and DSN"},
    {20009,"failed to connect remote DSN,connection to QMDB refused",
            "failed to connect remote DSN,connection to QMDB refused",
            "Please check the correct user name, password and DSN"},
    {20010,"maximum number of QMDB remote connection exceeded",
            "maximum number of QMDB remote connection exceeded",
            "Please release an invalid remote link"},
    {20011,"maximum number of QMDB local connection exceeded",
            "maximum number of QMDB local connection exceeded",
            "Please release an invalid local links"},
    {20012,"maximum number of QMDB replication connection exceeded",
            "maximum number of QMDB replication connection exceeded",
            "Please release an invalid rep links"},
    {20013,"attribute of DSN does not exist", 
            "attribute of DSN does not exist", 
            "Check the DSN configuration file"},
    {20014,"user already exists", 
            "user already exists", 
            "Please modify your user name"},
    {20015,"user to modify doex not exist", 
            "user to modify doex not exist", 
            "Please create a user"},
    {20016,"can not create tablespace", 
            "can not create tablespace", 
            "Check first the table space is already exist"},
    {20017,"can not modify tablespace", 
            "can not modify tablespace", 
            "Please first check the modified table space property exists"},
    {20018,"can not drop tablespace", 
            "can not drop tablespace", 
            "Check if the tablespace exists"},
    {20019,"tablespace already exists",
            "tablespace already exists", 
            "Please drop the tablespace"},
    {20020,"tablespace does not exist",
            "tablespace does not exist", 
            "Please create tablespace"},
    {20021,"can not create table",
            "can not create table", 
            "Check if the table already exists"},
    {20022,"can not drop table", 
            "can not drop table", 
            "Check if the table already exists"},
    {20023,"failure to create user", 
            "failure to create user", 
            "Check if user exists"},
    {20024,"failure to modify user's password",
            "failure to modify user's password", 
            "Check that the password is illegal"},
    {20025,"failure to modify user's privilege",
            "failure to modify user's privilege", 
            "Please check the user's privilege is valid."},
    {20026,"failure to drop user", 
            "failure to drop user", 
            "Check if user exists"},
    {20027,"can not drop system table", 
            "can not drop system table",
            "Not allowed to delete system tables"},
    {20028,"invalid data source configuration",
            "invalid data source configuration", 
            "Please check the correct Oracle link information"},
    {20029,"sequence does not exist", 
            "sequence does not exist", 
            "Please create a sequence"},
    {20030,"sequence already exists", 
            "sequence already exists", 
            "Please drop a sequence"},
    {20031,"can not create job", 
            "can not create job", 
            "Please check first whether a job already exists"},
    {20032,"can not update job", 
            "can not update job", 
            "Please check the correct update job properties"},
    {20033,"can not drop job", 
            "can not drop job", 
            "Please check first whether a job already exists"},
    {20034,"job does not exist",
            "job does not exist", 
            "Please create a job"},
    {20035,"job already exists",
            "The name for a job has been used",
            "Specify a unique name for the job in job configuration file"},
    {20036,"no SQL is set for a job",
            "The configuration item 'sql' of the job is empty",
            "Set a correct sql for the job in the job configuration file"},
    {20037,"invalid configuration of job", 
            "invalid configuration of job", 
            "Please check configuration of job"},
    {20038,"invalid tablespace name", 
            "Invalid characters were found in the tablespace name. The name can contain only letters, digits, and underscores",
            "Specify a tablespace name that contains only valid characters in the system configuration file"},
    {20039,"maximum number of tablespace exceeded",
            "Too many tablespaces", 
            "Try to reduce the number of the tablespace in the system configuration file"},
    {20040,"invalid tablespace id",
            "Tablespace ID is not within the legal range",
            "Correct the value of 'table-space-id' in the system configuration file"},
    {20041,"Version mismatch.",
            "Current QMDB version does not match what is created in shared memory",
            "Check which version is you want. If you want the one in memory,please install the QuickMDB with the same version,otherwise, destroy the QuickMDB first and then create and start it"},
    {20042,"too long time between Start and Create operation - exceeding",
            "Not start QuickMDB in required time after it is created",
            "Recreate QuickMDB"},
    {20043,"maximum number of user exceeded",
            "maximum number of user exceeded",
            "Remove the invalid user"},
    {20044,"maximum number of job exceeded",
            "maximum number of job exceeded",
            "remove the invalid job"},
    {20045,"the tablespace ID of table is not found",
            "The item 'table-space-id' in the table's struct configuration file is invalid",
            "Specify a valid tablespace ID in the table's struct file"},
    {20050,"DSN already exist.", 
            "DSN already exist.", 
            "use a unique dsn name."},
            
    {20101,"table in the property configuration file is not found",
            "table in the property configuration file is not found",
            "Specify a tablename that exists"},
    {20102,"table already exists",
            "The same table name has been used for another table", 
            "Specify a unique value for the 'table-name' in the table's struct file"},
    {20103,"invalid table name",
            "Invalid characters were found in the table name. The name can contain only letters, digits, and underscores", 
            "Specify a table name that contains only valid characters in the table's struct file"},
    {20104,"maximum number of table exceeded",
            "Too many user tables", 
            "Try to reduce the number of the tables"},
    {20105,"table ID already exists",
            "The same table ID has been used for another table", 
            "Correct the value of 'table-id' in the table's struct file"},
    {20106,"invalid table id - not between 0 and 449",
            "Table ID is not within the legal range", 
            "Correct the value of 'table-id' in the table struct file"},
    {20107,"index already exists",
            "The index name has been used for another index of the table", 
            "Sepcify a unique name for the index in the table's struct file"},
    {20108,"index does not exist",
            "index does not exist", 
            "Please create an index, and then using"},
    {20109,"No index created on table",
            "A table should at least have an index", 
            "Add an index for the table in the table's struct configuration file"},
    {20110,"maximum number of index exceeded in table",
            "Too many indexs on one table", 
            "Try to reduce the number of the table's index in the table's struct file"},
    {20111,"invalid index name in table",
            "Invalid characters were found in the index name,The name can contain only letters, digits, and underscores", 
            "Specify a index name that contains only valid characters in the system configuration file"},
    {20112,"Invalid column position for the index of table",
            "The column position does not exist in the table", 
            "Correct the column position of the index in the table's struct file"},
    {20113,"maximum number of column exceeded",
            "Too many columns for a table", 
            "Try to reduce the number of the columns in the table's struct file"},
    {20114,"column already exists in table",
            "The same name has been used for another column of the table", 
            "Sepcify a unique name for the column in the table's struct file"},
    {20115,"column does not exist in table",
            "Operation column does not exist", 
            "Please check whether the column is a legitimate, if legitimate, create a column"},
    {20116,"column position does not exist in table",
            "The 'column-pos' of the table is not continuous", 
            "Adjust the 'column-pos' in the table's struct file to make it continuous"},
    {20117,"invalid column name in table",
            "Invalid characters were found in the column name. The name can contain only letters, digits, and underscores", 
            "Specify a valid name that contains only valid characters in the table's struct file"},
    {20118,"invalid data type for column in table",
            "Data type of the column is invalid", 
            "Correct the data type of the column in the table's struct file"},
    {20119,"column length in table is invalid or exceeds maximum length",
            "Column length is not within the legal range", 
            "Correct the column length in the table's struct file"},
    {20120,"the default value's length of the column is grater than the defined length in table",
            "The length of a column's default value is invalid", 
            "Correct the default value in the table's struct configuration file"},
    {20121,"invalid default value whose length is for a date stamp column",
            "The length of the data stamp value is invalid", 
            "Correct the default value in the table's struct configuration file"},
    {20122,"invalid defualt value for column in table,data type mismatch",
            "The data type of the defualt value does not match that of the column", 
            "Correct the default value in the table's struct configuration file"},
    {20123,"invalid replication type for column",
            "The replication type cannot be identified", 
            "Correct the replication type for the column in the table's struct configuration file"},
    {20124,"No column in table",
            "A table should at least have a column", 
            "Add columns for the table in its struct file"},
    {20125,"no primary key in table",
            "A table should at least have a primary key column", 
            "Add a primary key for the table in its struct file"},
    {20126,"invalid column position for the primary key of talbe",
            "The column position does not exist in the table", 
            "Correct the primary key's column position in the table's struct file"},
    {20127,"maximum number of primary key columns exceeded",
            "Too many columns for a primary key", 
            "Try to reduce the number of the primary key columns in the table's struct file"},
    {20128,"can not set primary key column in table nullable",
            "Configuration iterm 'Null-able' of a primary key column is set to 'Y'. Primary key column can not be null", 
            "Set the item 'Null-able' of the primary key column to 'N'"},
    {20129,"can not set default value for primary key column in table",
            "Configuration iterm 'Default-Value' of a primary key column is not empty. Primary key column can not have default value", 
            "Set the item 'Default-Value' of the primary key column to an empty string"},
    {20130,"a record length of table is invalid or exceeds maximum length",
            "The table's record length is not within the legal range", 
            "Adjust the record to make the length  in legal range"},
    {20131,"records of table on one page of tablespace maximum number of records per page exceeds",
            "Page size is too large or record size is too small", 
            "Either:Decrease the page size of the tablespace in the system configuration file,Increase the record size of the table's record length"},
    {20132,"PK value is conflict",
            "PK value is conflict", 
            "Please modify the primary key of the inserted value"},
    {20133,"table attribute already exists",
            "Table attribute already exists", 
            "Please delete operations table properties"},
    {20134,"table attribute does not exist",
            "Table attribute has not been created", 
            "Create table properties"},
    {20135,"invalid replication type for table",
            "Synchronization of the table type is invalid", 
            "Modify the table replication type"},
    {20136,"failure to create index",
            "Failed to create index", 
            "Check first if the index already exists, then check whether SQL is valid"},
    {20137,"failure to drop index",
            "index does not exist.", 
            "Please create index"},
    {20138,"failure to create primary key",
            "Failed to create the primary key", 
            "Please check if the primary key already exists, and then examine the legality of the primary key column"},
    {20139,"failure to drop primary key",
            "faield to drop the primary key", 
            "Please create primary key"},
    {20140,"missing column",
            "Missing column",
            "Please add missing columns"},
    {20141,"invalid data value for column",
            "invalid data value for column",
            "Please modify valid data types"},
    {20142,"size of base index segment exceeds the size of data segment",
            "size of base index segment exceeds the size of data segment",
            "alter the configuration item [data-size] in QuickMDB_SYS_%s.xml"},
    {20143,"no free conflicting index node available",
            "no free conflicting index node available",
            "Modify the record-counts parameter in the configuration file of the table"},
    {20144,"Table does not exist.",
            "Table does not exist or if there is no table configuration file.",
            "First create the table, and then in the action."},
    {20145,"Table's index type is invalid.",
            "Table's index type is invalid.",
            "check index type ,it must be HASH/MHASH/BTREE"},
    {20146,"btree index does not support composite index.",
        "btree index does not support composite index.",
        "check btree index ,it must be one column index , or change index type to hash /mhash type index"},
    {20147,"add index failed.",
        "add index failed.",
        "check index type , table count"},
    {20148,"attached index num not equal to  expected num",
        "attached index num not equal to  expected num.",
        "check index num in dba_tables and dba_index"},
    {20149,"qmdb system error, index info not be initialized.",
        "qmdb system error, index info not be initialized.",
        "collect log file ,and contact qmdb developer."},
    {20150,"qmdb system error, calculate index value failed",
        "qmdb system error, calculate index value failed.",
        "collect log file ,and contact qmdb developer."},
            
    {20201,"null or invalid SQL statement",
            "null or invalid SQL statement",
            "Please check the SQL is valid."},
    {20202,"maximum lenth of SQL exceeded",
            "maximum lenth of SQL exceeded",
            "Please check whether the length of the SQL 4K"},
    {20203,"type of SQL statement not supported",
            "type of SQL statement not supported",
            "Check that the type of SQL operation is lawful, it must be INSERT/UPDATE/DELETE/SELECT"},
    {20204,"SQL does not end with a semicolon ';'",
            "SQL does not end with a semicolon ';'",
            "Please add end tail of the SQL identifier"},
    {20205,"invalid identifier ",
            "invalid identifier", 
            "Please check your SQL"},
    {20206,"SQL is not SET before OPEN or EXECUTE operation",
            "SQL is not SET before OPEN or EXECUTE operation",
            "Please check your SQL"},
    {20207,"not all parameters bound",
            "not all parameters bound", 
            "Please check your SQL"},
    {20208,"duplicate parameter name",
            "duplicate parameter name", 
            "Please check your SQL"},
    {20209,"invalid parameter name, parameter not found in SQL",
            "invalid parameter name, parameter not found in SQL", 
            "Please check your SQL"},
    {20210,"invalid parameter index",
            "invalid parameter index", 
            "Please check your SQL"},
    {20211,"invalid data type to parameter",
            "invalid data type to parameter", 
            "Please check your SQL"},
    {20212,"value is too long for parameter - size of buffer exceeds maximum",
            "value is too long for parameter - size of buffer exceeds maximum", 
            "Please check your SQL"},
    {20213,"OPEN method should be called befor NEXT",
            "OPEN method should be called befor NEXT", 
            "Please check your SQL"},
    {20214,"column not found in query SQL",
            "column not found in query SQL", 
            "Please check your SQL"},
    {20215,"invalid column index",
            "invalid column index", 
            "Please check your SQL"},
    {20216,"can not convert the column value into a number",
            "can not convert the column value into a number", 
            "Please check your SQL"},
    {20217,"can not convert the column value into a date string",
            "can not convert the column value into a date string", 
            "Please check your SQL"},
    {20218,"can not convert the column value into parts of a date",
            "can not convert the column value into parts of a date", 
            "Please check your SQL"},
    {20219,"can not convert the column value into a blob",
            "can not convert the column value into a blob", 
            "Please check your SQL"},
    {20220,"can not convert a NULL column into a value",
            "can not convert a NULL column into a value", 
            "Please check your SQL"},
    {20221,"can not set variable to NULL",
            "can not set variable to NULL", 
            "Please check your SQL"},
    {20222,"parameter of FLOAT type not supported in dynamic SQL",
            "parameter of FLOAT type not supported in dynamic SQL", 
            "Please check your SQL"},
    {20223,"parameter of BLOB type not supported in dynamic SQL",
            "parameter of BLOB type not supported in dynamic SQL", 
            "Please check your SQL"},
    {20224,"invalid method to set parameter value",
            "invalid method to set parameter value", 
            "Please check your SQL"},
    {20225,"number of the columns and the values is not the same in the INSERT SQL",
            "number of the columns and the values is not the same in the INSERT SQL", 
            "Please check your SQL"},
    {20226,"data type of the value does not match type of column",
            "data type of the value does not match type of column", 
            "Please check your SQL"},
    {20227,"function not supported",
            "function not supported", 
            "Please check your SQL"},
    {20228,"NULL value is not allowed for column",
            "NULL value is not allowed for column", 
            "Please check your SQL"},
    {20229,"executing SQL timed out",
            "executing SQL timed out", 
            "Please check your SQL"},
    {20230,"error in calculating expression value in WHERE condition",
            "error in calculating expression value in WHERE condition", 
            "Please check your SQL"},
    {20231,"maximum number of columns to order by exceeded",
            "maximum number of columns to order by exceeded", 
            "Please check your SQL"},
    {20232,"invalid value type in SQL",
            "invalid value type in SQL", 
            "Please check your SQL"},
    {20233,"error in calculating expression value in SQL",
            "error in calculating expression value in SQL", 
            "Please check your SQL"},
    {20234,"invalid data type in SQL",
            "invalid data type in SQL", 
            "Please check your SQL"},
    {20235,"invalid data length  in SQL",
            "invalid data length  in SQL", 
            "Please check your SQL"},
    {20236,"error occurred in getting data from memory",
            "error occurred in getting data from memory", 
            "Please check your SQL"},
    {20237,"error occurred in operating on index column",
            "error occurred in operating on index column", 
            "Please check your SQL"},
    {20238,"invalid time value",
            "invalid time value", 
            "Please check your SQL"},
    {20239,"maximum size of rollback segment exceeded,rollback segment is full",
            "maximum size of rollback segment exceeded,rollback segment is full", 
            "Please check your SQL"},
    {20240,"too much number of SQL exceeding not commited,can not find free rollback unit",
            "too much number of SQL exceeding not commited,can not find free rollback unit", 
            "Please check your SQL"},
    {20241,"Fill QMDB info error",
            "Fill QMDB info error", 
            "Check whether the SQL is effective"},
    {20242,"SetParam error",
            "SetParam error", 
            "Please contact QMDB Admin"},
    {20243,"Flush data from QMDB error",
            "Synchronous data flush failed", 
            "Please contact QMDB Admin"},
    {20244,"stop execute SQL	",
            "To stop the execution of SQL", 
            "Please check whether the process has exited"},
    {20245,"Column property does not exist",
            "Column property does not exist", 
            "Please check the table configuration file, see the column support those attributes"},
    {20246,"Does not support batch binding",
            "Does not support batch binding", 
            "Please single parameter setting"},
    
    {20301,"unable to create shared memory segment", 
            "An operating system error occurred while attempting to create or open a file", 
            "Note the operating system error message or number and contact your system administrator"},
    {20302,"unable to attach to shared memory segment",
            "unable to attach to shared memory segment", 
            "Note the operating system error message or number and contact your system administrator"},
    {20303,"unable to detach from shared memory segment",
            "unable to detach from shared memory segment",
            "Note the operating system error message or number and contact your system administrator"},
    {20304,"unable to remove shared memory segment",
            "unable to remove shared memory segment",
            "Note the operating system error message or number and contact your system administrator"},
    {20305,"shared memory already exists",
            "shared memory already exists",
            "Please destroy a shared memory, and then re-create"},
    {20306,"shared memory dose not exist",
            "shared memory dose not exist", 
            "First create the shared memory"},
    {20307,"out of memory",
            "The operating system has run out of memory",
            "Take action to make more memory available to the program"},
    {20308,"failure to create thread",
            "failure to create thread", 
            "Take action to make more memory available to the program"},
    {20309,"failure to set thread attribute",
            "failure to set thread attribute", 
            "Take action to make more memory available to the program"},
    {20310,"failure to join with thread",
            "failure to join with thread", 
            "Take action to make more memory available to the program"},
    {20311,"failed to make directory",
            "failed to make directory", 
            "Fix the operating system error"},
    {20312,"error in opening file",
            "An operating system error occurred while attempting to create or open a file", 
            "Fix the operating system error"},
    {20313,"error in reading file",
            "error in reading file", 
            "Fix the operating system error"},
    {20314,"error in writing file",
            "error in writing file",
            "Fix the operating system error"},
    {20315,"error in removing file",
            "error in removing file",
            "Fix the operating system error"},
    {20316,"error in closing file",
            "error in closing file", 
            "Fix the operating system error"},
    {20317,"failed to backup file",
            "failed to backup file",
            "Fix the operating system error"},
    {20318,"error in opening directory",
            "error in opening directory", 
            "Fix the operating system error"},
    {20319,"failure to get file size",
            "failure to get file size", 
            "Fix the operating system error"},
    {20320,"failure to lock file",
            "failure to lock file", 
            "Fix the operating system error"},
    {20321,"failure to unlock file",
            "failure to unlock file", 
            "Fix the operating system error"},
    {20322,"file does not exist",
            "file does not exist", 
            "Please check file  are correct"},
    {20323,"The directory does not exist",
            "The directory does not exist", 
            "Please create the directory"},
    {20324,"error in setting mutex attribute",
            "error in setting mutex attribute", 
            "Note the operating system error message or number and contact your system administrator"},
    {20325,"failed to lock mutex",
            "failed to lock mutex", 
            "Note the operating system error message or number and contact your system administrator"},
    {20326,"failed to unlock mutex",
            "failed to unlock mutex", 
            "Note the operating system error message or number and contact your system administrator"},
    {20327,"popen returns a error",
            "popen returns a error", 
            "Note the operating system error message or number and contact your system administrator"},
    {20328,"Environment variable is not set",
            "The environment variable is not set", 
            "Set the environment variable"},
    {20329,"Create file failed",
            "Maybe  file path is wrong", 
            "Fix file path"},
    {20330,"Not enough free diskspace",
            "too many files maybe", 
            "delete  some useless files"},        
            
    {20401,"socket creation failure",
            "Socket handles the maximum limit is reached", 
            "Adjusting system handles up to maximum limit"},
    {20402,"failed  to bind socket to port",
            "The bind system call failed on the socket", 
            "Check additional information for operating system error. Try connecting again"},
    {20403,"failed to start listener at the socket",
            "The listen system call failed on the socket", 
            "Check additional information for operating system error. Try connecting again"},
    {20404,"failed  to accept a connection",
            "The accept system call failed on the socket", 
            "Check additional information for operating system error. Try connecting again"},
    {20405,"failed  to set socket options",
            "failed  to set socket options", 
            "Please contact QMDB Admin"},
    {20406,"connect to host failed",
            "Connection attempt to remote host has failed. Probably server on the remote host is not up", 
            "Start the server process on the remote host, and retry the operation"},
    {20407,"connection refused",
            "connection refused", 
            "Please check remort server"},
    {20408,"invalid socket",
            "invalid socket", 
            "Please contact QMDB Admin"},
    {20409,"data receive failure",
            "I/O error occurred while attempting network read operation", 
            "Contact QuickMDB Support Services"},
    {20410,"data send failure",
            " I/O error occurred while attempting network write operation", 
            "Contact QuickMDB Support Services"},
    {20411,"invalid IP address",
            "invalid IP address",
            "Please check ip"},
    {20412,"failed to select a connection",
            "failed to select a connection", 
            "Please contact QMDB Admin"},
    {20413,"socket is closed",
            "socket is closed",
            "Please check network is OK"},
    {20414,"failed to get host name",
            "failed to get host name",
            "Please contact QMDB Admin"},
    {20415,"gethostbyname returns NULL,check if IP is invalid",
            "gethostbyname returns NULL",
            "Check that the IP is effectively"},
    {20416,"failed to start billingNTC engine",
            "failed to start billingNTC engine",
            "Contact QuickMDB Support Services"},
            
    
    {20501,"invalid format of QuickMDB command line",
            "Command line does not comply with the prescribed format", 
            "Modify the command as the folowing format: QuickMDB 'dsn=dsn_name;uid=user_id;pwd=password;oper=oper_type'"},
    {20502,"invalid operation type in QuickMDB command line",
            "Operation type in the command line is not supported by QuickMDB",
            "Modify the operation type as one of the follows according to actual: create、start、stop、destroy"},
    {20503,"QuickMDB is not running",
            "Can not execute the command while QuickMDB is not running",
            "Start QuickMDB first and then execute your command"},
    {20504,"missing DSN",
            "DSN is empty", 
            "Check to see if the DSN is valid"},
    {20505,"missing username",
            "Does not provide a user name", 
            "Check that the user name is valid"},
    {20506,"missing password",
            "Password is invalid", 
            "Check that the password is valid"},
    {20507,"system process of QuickMDB still exists",
            "Not all the QuickMDB system processes are stopped successfully last time. When you want to create a new QuickMDB, all the system processes started by the old QuickMDB should be stoped first", 
            "Killed the system process of the DSN manually; and then try QuickMDB create command again"},
    {20508,"Process mdbDbRep of QuickMDB still exists",
            "Process mdbDbRep is not stopped successfully when you want to create QuickMDB", 
            "Killed the process mdbDbRep of the DSN manually; and then try QuickMDB create command again"},
    {20509,"failed to start process",
            "QuickMDB will start its system processes when it starts to run. Some system processes may not start successfully for some reasons", 
            "Check the log of the process started failed and find the cause. Correct the cause of the preceding errors. And then try the START command again"},
    {20510,"failed to kill process ",
            "When to stop the processes registered to QuickMDB, some process may not be stopped in required time and can not be killed either for some exception", 
            "try to kill it manually"},
    {20511,"process does not exist",
            "The process monitored by QuickMDB does not exist while the state in memory is not 'PSTOP'", 
            "Report the error to the QuickMDB administrator"},
    {20512,"failed to restart process",
            "QuickMDB can not start the process after killed it for heartbeat timeout", 
            "Report the error to the QuickMDB administrator"},
    {20513,"configuration of tablespace in file is different from in shared memory - in file",
            "The configuration of the tablespace may be changed after QuickMDB was created", 
            "Either recreate the QuickMDB or modify the configuration to keep consistent with what in shared memory"},
    {20514,"table in configuration file does not exists in shared memory",
            "The configuration file of the table may be added after QuickMDB was created",
            "Either recreate the QuickMDB or remove the configuration  file of the table"},
    {20515,"configuration of table  in file is different from in shared memory ",
            "The configuration of the table may be changed after QuickMDB was created", 
            "Either recreate the QuickMDB or modify the configuration to keep consistent with what in shared memory"},
    {20516,"too many connection; mdbAgent can most start threads to process clients connection",
            "Number of clients exceeds the maximum number mdbAgent can hold", 
            "Close the unused connections and retry the operation"},
    {20517,"can not find a user of QuickMDB with administrator privilege",
            "There's no user with the administrator privilege in the system configuration file", 
            "Configure an user and set the 'access' to 'A'. Rectreate and start QuickMDB"},
    {20518,"failed to connect database",
            "Can not connect to database.This can result from any of the following situations:User or password is invalid; configuration of database in local host is incorrect; there is a network problem", 
            "Check if the 'user', 'password' or 'db-id' of the oracle in system configuration is correct. If no proplem with the configuration, contact Oracle DBA"},
    {20519,"invalid oracle login information; user, password or DSN is empty",
            "'user', 'password' or 'db-id' of the oracle in system configuration is null", 
            "Set correct values for the oracle configuration. Rectreate and start QuickMDB"},
    {20520,"replication synchronous area is not created while the configuration item [is-rep] is yes",
            "replication synchronous area is not created",
            "Please re-create QMDB"},
    {20521,"maximum length of routing list exceeded",
            "maximum length of routing list exceeded", 
            "Please reduce the number of routes"},
    {20522,"process registration failed",
            "process registration failed", 
            "Check if the process exists"},
    {20523,"process already exists",
            "process already exists", 
            "Please stop the process, and then restart "},
    {20524,"maximum number of registered process exceeded",
            "maximum number of registered process exceeded", 
            "Please stop useless process"},
    {20525,"maximum number of sequence exceeded",
            "maximum number of sequence exceeded", 
            "Please remove invalid sequences"},
    {20526,"null or invalid parameter ",
            "null or invalid parameter",
            "Please contact QMDB Admin"},
    {20527,"invalid integer value ",
            "invalid integer value", 
            "Please contact QMDB Admin"},
    {20528,"invalid boolean value",
            "invalid boolean value",
            "Please contact QMDB Admin"},
    {20529,"invalid value for a date stamp data",
            "invalid value for a date stamp data", 
            "Please contact QMDB Admin"},
    {20530,"invalid data type",
            "invalid data type", 
            "Configure a valid data type"},
    {20531,"string is overflow to convert to a long long value ",
            "string is overflow to convert to a long long value", 
            "Please contact QMDB Admin"},
    {20532,"invalid value",
            "invalid value", 
            "Please contact QMDB Admin"},
    {20533,"file name is too long exceeding maximum length",
            "file name is too long exceeding maximum length", 
            "Please contact QMDB Admin"},
    {20534,"path name is null",
            "path name is null",
            "Please contact QMDB Admin"},
    {20535,"path name is too long exceeding maximum length",
            "path name is too long exceeding maximum length",
            "Please contact QMDB Admin"},
    {20536,"invalid sequence",
            "invalid sequence", 
            "Please check the sequence exists in the dba_sequence table"},
    {20537,"to update blob column is not supported",
            "to update blob column is not supported",
            "Please update other types of columns"},
    {20538,"invalid time string format, should be 'YYYYMMDDHH24MISS'",
            "invalid time string format, should be 'YYYYMMDDHH24MISS'",
            "Correct the time string formort"},
    {20539,"invalid value for day of a datetime", 
            "invalid value for day of a datetime", 
            "Please contact QMDB Admin"},
    {20540,"invalid value for month of a datetime", 
            "invalid value for month of a datetime,it must be 1-12",
            "Please contact QMDB Admin"},
    {20541,"invalid value for a second value ",
            "invalid value for a second value,it must be 0-59", 
            "Please contact QMDB Admin"},
    {20542,"can not find path name", 
            "can not find path name",
            "Please check the path configuration"},
    {20543,"failed to load table from database",
            "failed to load table from database", 
            "Please check the load-SQL parameter of the table are in a valid configuration"},
    {20544,"can not replicate tables biginning with 'dba_' from oracle to QMDB",
            "can not replicate tables biginning with 'dba_' from oracle to QMDB", 
            "System table data cannot be synchronized, self-defined table's name must not begin with the DBA_"},
    {20545,"invalid data format in replication area", 
            "invalid data format in replication area", 
            "Please contact QMDB Admin"},
    {20546,"invalid data format in replication file",
            "invalid data format in replication file", 
            "Please contact QMDB Admin"},
    {20547,"can not execute other than DML in C/S mode", 
            "can not execute other than DML in C/S mode", 
            "Please contact QMDB Admin"},
    {20548,"can not execute DML in offline mode", 
            "can not execute DML in offline mode", 
            "Please contact QMDB Admin"},
    {20549,"invalid table property", 
            "invalid table property", 
            "Please check table properties on the table exists in the configuration file, if the specified table does not exist, property is illegal"},
    {20550,"invalid property of QuickMDB system configuration",
            "invalid property of QuickMDB system configuration", 
            "Check the DSN configuration file"},
    {20551,"can not set length of column smaller than former length",
            "can not set length of column smaller than former length", 
            "Set the column's length must be greater than the defined length of column"},
    {20552,"file of table does not exist,a table's struct and property files don't match",
            "There is only the struct or the property file of a table exists, missing another configuration file", 
            "Check if the table is valid. If so, make sure both the STRUCT and the PROPERTY configuration file of the table in the DSN's directory. Otherwise, remove the single file"},
    {20553,"loading configuration file failed,please check if the file conforms to the XML syntax rules",
            "There is syntax error in the configuration file", 
            "Check and modify the configuration file according to XML syntax rule"},
    {20554,"invalid value for configuration item",
            "invalid value for configuration item",
            "Please check the legality of the configuration item in the configuration file values"},
    {20555,"invalid value for item 'type' of data source in system configuration file.",
            "Data source type is the type of database QuickMDB will connect. And only oracle database is supported for now",
            "If the data for QuickMDB is in oracle database, set 'type' to 'oracle'. QuickMDB cannot support other database"},
    {20556,"invalid DSN name in system configuration file.",
            "DSN name in the configuration file is not the same as the name contained in the file name",
            "Correct the DSN values in the system configuration file"},
    {20557,"invalid DSN value",
            "DSN value should between 0 and the maximum value. And can not be the same with the value of other QuickMDB in the same host", 
            "Correct the DSN values in the system configuration file"},
    {20558,"invalid value for 'kill-time',should be grater than 0",
            "The value of the configuration item is not within the legal range", 
            "Correct the values in the system configuration file"},
    {20559,"invalid value for 'Delay-time', should be grater than 0",
            "The value of the configuration item is not within the legal range", 
            "Correct the values in the system configuration file"},
    {20560,"invalid value for 'Clean-Time', should be grater than 0.", 
            "The value of the configuration item is not within the legal range", 
            "Correct the values in the system configuration file"},
    {20561,"invalid value for 'Rep-Type',should be 1",
            "The value of the configuration item is not within the legal range", 
            "Correct the values in the system configuration file"},
    {20562,"invalid value for 'ora-rep-counts',should be grater than 0.",
            "The value of the configuration item is not within the legal range", 
            "Correct the values in the system configuration file"},
    {20563,"the value of 'HeartBeatFatal'is less than the value of 'HeartBeatWarning'",
            "The value of 'HeartBeatFatal' should be grater than the value of 'HeartBeatWarning'", 
            "Correct the values in the system configuration file"},
    {20564,"Cannot set 'is-peer-rep' to 'Y' while 'is-rep' is 'N'",
            "Disaster replication(is-peer-rep) can only be set to 'Y' when stdandby replication（is-rep) is 'Y'", 
            "Either modify 'is-rep' to 'Y' or modify 'is-peer-rep' to 'N'"},
    {20565,"invalid value for 'manager-size',should be grater than 0 and not exceeding the maximum",
            "The value of the configuration item is not within the legal range", 
            "Correct the value in the system configuration file."},
    {20566,"invalid value for 'rep-file-timeout',should be grater than 0",
            "The value of the configuration item is not within the legal range", 
            "Correct the value in the system configuration file."},
    {20567,"invalid value for 'Is-Zip-Time',should be 'Y','N' or 'L'",
            "The value of the configuration item is not within the legal range", 
            "Correct the value in the system configuration file."},
    {20568,"unknown configuration item in xml file",
            "The name of the configuration item is invalid, spelling mistakes or useless", 
            "Correct the name of the item or remove it if it is useless"},
    {20569,"configuration item not found in file",
            "The item is not configured in the configuration file", 
            "Configure the item correctly and retry"},
    {20570,"string out of bound",
            "Copy the string is too long, resulting in duplicated string inconsistent with the source string", 
            "Modify the copied string length"},
    {20571,"process registration failure",
            "Process management area is full and cannot be registered", 
            "Please release invalid process registration information "},
    {20572,"Brush out the cache log failure",
            "Brush out the cache log failure", 
            "Please contact QMDB Admin"},
    {20573,"File already exists",
            "File already exists", 
            "Delete existing file"},
    {20574,"Invalid parameter",
            "The input parameters may be invalid", 
            "Please check the function of the input parameters according to the log information release"},
            
    {20601,"package received not logon package",
            "package received not logon package", 
            "Please send the login packet"},
    {20602,"logon to remote server [%s/%s@%s] failed",
            "logon to remote server [%s/%s@%s] failed", 
            "Please check the correct login username, password and DSN"},
    {20603,"peer session id is not equal to current session id",
            "peer session id is not equal to current session id", 
            "Please check your program"},
    {20604,"failed to parser logon package",
            "failed to parser logon package", 
            "Please check the log package is valid"},
    {20605,"invalid format of CSP package received",
            "invalid format of CSP package received", 
            "Please contact QMDB Admin"},
    {20606,"invalid format of CSP package to send",
            "invalid format of CSP package to send", 
            "Please contact QMDB Admin"},
    {20607,"invalid AVP code",
            "invalid AVP code", 
            "Please contact QMDB Admin"},
    {20608,"can not find free AVP item",
            "can not find free AVP item", 
            "Please contact QMDB Admin"},
    {20609,"can not set AVP NULL",
            "can not set AVP NULL", 
            "Please contact QMDB Admin"},
    {20610,"can not set type of AVP",
            "can not set type of AVP", 
            "Please contact QMDB Admin"},
    {20611,"failed to copy AVP item",
            "failed to copy AVP item", 
            "Please contact QMDB Admin"},
    {20612,"AVP does not exist", 
            "AVP does not exist", 
            "Please contact QMDB Admin"},
    {20613,"invalid type of AVP code",
            "invalid type of AVP code", 
            "Please contact QMDB Admin"},
    {20614,"maximum number of sequence exceeded", 
            "maximum number of sequence exceeded", 
            "Please contact QMDB Admin"},
    {20615,"invalid client sequence value",
            "invalid client sequence value", 
            "Please contact QMDB Admin"},
    {20616,"Parse csp package error",
            "Parse csp package error", 
            "Please contact QMDB Admin"}
};

/******************************************************************************
* 函数名称	:  TMdbErrorHelper
* 函数描述	:  构造
* 输入		:  
* 输入		:  
* 输出		:  
* 返回值	: 
* 作者		:  jin.shaohua
*******************************************************************************/
TMdbErrorHelper::TMdbErrorHelper()
{
	m_iErrCode = 0;
	//m_sTemp[0] = 0;
	m_psTemp = NULL;
    m_mapErrorDesc.clear();
}

/******************************************************************************
* 函数名称	:  
* 函数描述	:  
* 输入		:  
* 输入		:  
* 输出		:  
* 返回值	:  0 - 成功!0 -失败
* 作者		:  jin.shaohua
*******************************************************************************/
TMdbErrorHelper::~TMdbErrorHelper()
{
	SAFE_DELETE(m_psTemp);
    Clear();
}
/******************************************************************************
* 函数名称	:  Clear
* 函数描述	:  清理
* 输入		:  
* 输入		:  
* 输出		:  
* 返回值	:  0 - 成功!0 -失败
* 作者		:  jin.shaohua
*******************************************************************************/
int TMdbErrorHelper::Clear()
{
    std::map<int ,TMdbError *>::iterator itor = m_mapErrorDesc.begin();
    for(;itor != m_mapErrorDesc.end();++itor)
    {
        SAFE_DELETE(itor->second);
    }
    m_mapErrorDesc.clear();
    return 0;
}

/******************************************************************************
* 函数名称	:  FillErrMsg
* 函数描述	:  填充错误信息
* 输入		:  
* 输入		:  
* 输出		:  
* 返回值	: 
* 作者		:  jin.shaohua
*******************************************************************************/
void TMdbErrorHelper::FillErrMsg(int iCode,const char* pszFormat, ...)
{
	if(0 != iCode)
	{
		//m_sTemp[0]=0;
		//char sTemp[1024] = {0};
		 if(NULL == m_psTemp)
        {
            m_psTemp = new char[40960];
            if(NULL == m_psTemp)
            {

                TADD_ERROR(ERR_OS_NO_MEMROY,"no memory to new error message buff.iCode=[%d]",iCode);
                return;
            }
        }
        else
        {

            m_psTemp[0]='\0';
        }
		
		va_list ap;//初始化参数指针
		va_start(ap, pszFormat);//初始化参数指针
		vsprintf(m_psTemp, pszFormat, ap);
		va_end(ap);//清理
		if(0 == m_iErrCode)
		{
			m_iErrCode = iCode;
			m_sErrMsg  = m_psTemp;
		}
		else
		{//有其他错误信息，添加
			m_sErrMsg += ",";
			m_sErrMsg += m_psTemp;
		}
	}
	else if(0 != m_iErrCode)
	{//清除
		m_iErrCode = iCode;
		m_sErrMsg  = "";
	}
	
}
/******************************************************************************
* 函数名称	:  InitErrorDescription
* 函数描述	:  初始化错误描述
* 输入		:  
* 输入		:  
* 输出		:  
* 返回值	:  0 - 成功!0 -失败
* 作者		:  jin.shaohua
*******************************************************************************/
int TMdbErrorHelper::InitErrorDescription()
{
    int iRet = 0;
    int i = 0;
    if(m_mapErrorDesc.size() > 0){return 0;}
    int iErrCounts = (sizeof(g_mdbErrors)/sizeof(g_mdbErrors[0]));
    while(i<iErrCounts)
    {
        TMdbError * pError = new (std::nothrow) TMdbError();
        pError->m_iCode = g_mdbErrors[i].m_iCode;
        pError->m_sBrief = g_mdbErrors[i].m_sBrief;
        pError->m_sCause = g_mdbErrors[i].m_sCause;
        pError->m_sAction = g_mdbErrors[i].m_sAction;
        if(FindErrorByCode(pError->m_iCode) != NULL)
        {
            CHECK_RET_BREAK(ERROR_UNKNOWN,"[%d:%s] is exist.",pError->m_iCode,pError->m_sBrief.c_str());
        }
        m_mapErrorDesc.insert(std::pair<int, TMdbError *>(pError->m_iCode, pError)) ;
        i++;
    }
    return iRet;
}

/******************************************************************************
* 函数名称	:  FindErrorByCode
* 函数描述	:  搜索error描述
* 输入		:  
* 输入		:  
* 输出		:  
* 返回值	:  0 - 成功!0 -失败
* 作者		:  jin.shaohua
*******************************************************************************/
TMdbError *TMdbErrorHelper::FindErrorByCode(int iCode)
{
    std::map<int,TMdbError *>::iterator itor =  m_mapErrorDesc.find(iCode);
    if(itor != m_mapErrorDesc.end())
    {
        return itor->second;
    }
    return NULL;
}

//}
