#ifndef _PARSER_H 
#define _PARSER_H 
#define TK_SELECT                          1
#define TK_UPDATE                          2
#define TK_DELETE                          3
#define TK_INSERT                          4
#define TK_ID                              5
#define TK_ASC                             6
#define TK_BY                              7
#define TK_DESC                            8
#define TK_NO                              9
#define TK_KEY                            10
#define TK_OFFSET                         11
#define TK_SYSDATE                        12
#define TK_IF                             13
#define TK_ANY                            14
#define TK_OR                             15
#define TK_AND                            16
#define TK_NOT                            17
#define TK_IS                             18
#define TK_MATCH                          19
#define TK_LIKE_KW                        20
#define TK_BETWEEN                        21
#define TK_IN                             22
#define TK_ISNULL                         23
#define TK_NOTNULL                        24
#define TK_NE                             25
#define TK_EQ                             26
#define TK_GT                             27
#define TK_LE                             28
#define TK_LT                             29
#define TK_GE                             30
#define TK_ESCAPE                         31
#define TK_BITAND                         32
#define TK_BITOR                          33
#define TK_LSHIFT                         34
#define TK_RSHIFT                         35
#define TK_PLUS                           36
#define TK_MINUS                          37
#define TK_STAR                           38
#define TK_SLASH                          39
#define TK_REM                            40
#define TK_CONCAT                         41
#define TK_COLLATE                        42
#define TK_BITNOT                         43
#define TK_SEMI                           44
#define TK_STRING                         45
#define TK_EXISTS                         46
#define TK_CREATE                         47
#define TK_TABLE                          48
#define TK_LP                             49
#define TK_RP                             50
#define TK_COMMA                          51
#define TK_INTEGER                        52
#define TK_CONSTRAINT                     53
#define TK_DEFAULT                        54
#define TK_NULL                           55
#define TK_REPTYPE                        56
#define TK_PRIMARY                        57
#define TK_DROP                           58
#define TK_TRUNCATE                       59
#define TK_INDEX                          60
#define TK_ON                             61
#define TK_ALTER                          62
#define TK_ADD                            63
#define TK_INTO                           64
#define TK_VALUES                         65
#define TK_FROM                           66
#define TK_SET                            67
#define TK_DOT                            68
#define TK_FIRST                          69
#define TK_DISTINCT                       70
#define TK_ALL                            71
#define TK_AS                             72
#define TK_WHERE                          73
#define TK_GROUP                          74
#define TK_HAVING                         75
#define TK_ORDER                          76
#define TK_LIMIT                          77
#define TK_USE                            78
#define TK_DATABASE                       79
#define TK_TABLESPACE                     80
#define TK_CONNECT                        81
#define TK_TO                             82
#define TK_ORACLE                         83
#define TK_MYSQL                          84
#define TK_PAGESIZE                       85
#define TK_ASKPAGE                        86
#define TK_STORAGE                        87
#define TK_USER                           88
#define TK_IDENTIFIED                     89
#define TK_ACCESSED                       90
#define TK_TABLESYS                       91
#define TK_MODIFY                         92
#define TK_COLUMN                         93
#define TK_LOAD                           94
#define TK_DATA                           95
#define TK_SEQUENCE                       96
#define TK_JOB                            97
#define TK_REMOVE                         98
#define TK_PARAMETER                      99
#define TK_PARAMTYPE                      100
#define TK_RENAME                         101
#define TK_NEXTVAL                        102
#define TK_CURRVAL                        103
#define TK_FLOAT                          104
#define TK_BLOB                           105
#define TK_VARIABLE                       106
#define TK_TO_TEXT                        107
#define TK_TO_BLOB                        108
#define TK_TO_NUMERIC                     109
#define TK_TO_INT                         110
#define TK_TO_REAL                        111
#define TK_ISNOT                          112
#define TK_END_OF_FILE                    113
#define TK_ILLEGAL                        114
#define TK_SPACE                          115
#define TK_UNCLOSED_STRING                116
#define TK_FUNCTION                       117
#define TK_AGG_FUNCTION                   118
#define TK_AGG_COLUMN                     119
#define TK_CONST_FUNC                     120
#define TK_UMINUS                         121
#define TK_UPLUS                          122
#define TK_ID_TABLENAME                   123
#define TK_ID_SEQUENCE                    124
#define TK_HINT                           125
#ifndef _TOKEN_NAME_ 
#define _TOKEN_NAME_ 
const char * const TokenName[] = { "", "TK_SELECT","TK_UPDATE","TK_DELETE","TK_INSERT","TK_ID","TK_ASC","TK_BY","TK_DESC","TK_NO","TK_KEY","TK_OFFSET","TK_SYSDATE","TK_IF","TK_ANY","TK_OR","TK_AND","TK_NOT","TK_IS","TK_MATCH","TK_LIKE_KW","TK_BETWEEN","TK_IN","TK_ISNULL","TK_NOTNULL","TK_NE","TK_EQ","TK_GT","TK_LE","TK_LT","TK_GE","TK_ESCAPE","TK_BITAND","TK_BITOR","TK_LSHIFT","TK_RSHIFT","TK_PLUS","TK_MINUS","TK_STAR","TK_SLASH","TK_REM","TK_CONCAT","TK_COLLATE","TK_BITNOT","TK_SEMI","TK_STRING","TK_EXISTS","TK_CREATE","TK_TABLE","TK_LP","TK_RP","TK_COMMA","TK_INTEGER","TK_CONSTRAINT","TK_DEFAULT","TK_NULL","TK_REPTYPE","TK_PRIMARY","TK_DROP","TK_TRUNCATE","TK_INDEX","TK_ON","TK_ALTER","TK_ADD","TK_INTO","TK_VALUES","TK_FROM","TK_SET","TK_DOT","TK_FIRST","TK_DISTINCT","TK_ALL","TK_AS","TK_WHERE","TK_GROUP","TK_HAVING","TK_ORDER","TK_LIMIT","TK_USE","TK_DATABASE","TK_TABLESPACE","TK_CONNECT","TK_TO","TK_ORACLE","TK_MYSQL","TK_PAGESIZE","TK_ASKPAGE","TK_STORAGE","TK_USER","TK_IDENTIFIED","TK_ACCESSED","TK_TABLESYS","TK_MODIFY","TK_COLUMN","TK_LOAD","TK_DATA","TK_SEQUENCE","TK_JOB","TK_REMOVE","TK_PARAMETER","TK_PARAMTYPE","TK_RENAME","TK_NEXTVAL","TK_CURRVAL","TK_FLOAT","TK_BLOB","TK_VARIABLE","TK_TO_TEXT","TK_TO_BLOB","TK_TO_NUMERIC","TK_TO_INT","TK_TO_REAL","TK_ISNOT","TK_END_OF_FILE","TK_ILLEGAL","TK_SPACE","TK_UNCLOSED_STRING","TK_FUNCTION","TK_AGG_FUNCTION","TK_AGG_COLUMN","TK_CONST_FUNC","TK_UMINUS","TK_UPLUS","TK_ID_TABLENAME","TK_ID_SEQUENCE","TK_HINT",};

#endif
#endif
